config/routes.rb
Rails.application.routes.draw do
  resources :verifications
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/verification.rb
class Verification < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/verifications_controller.rb
class VerificationsController < ApplicationController
  before_action :set_verification, only: %i[ show edit update destroy ]

  # GET /verifications or /verifications.json
  def index
    @verifications = Verification.all
  end

  # GET /verifications/1 or /verifications/1.json
  def show
  end

  # GET /verifications/new
  def new
    @verification = Verification.new
  end

  # GET /verifications/1/edit
  def edit
  end

  # POST /verifications or /verifications.json
  def create
    @verification = Verification.new(verification_params)

    respond_to do |format|
      if @verification.save
        format.html { redirect_to @verification, notice: "Verification was successfully created." }
        format.json { render :show, status: :created, location: @verification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verifications/1 or /verifications/1.json
  def update
    respond_to do |format|
      if @verification.update(verification_params)
        format.html { redirect_to @verification, notice: "Verification was successfully updated." }
        format.json { render :show, status: :ok, location: @verification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verifications/1 or /verifications/1.json
  def destroy
    @verification.destroy
    respond_to do |format|
      format.html { redirect_to verifications_url, notice: "Verification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verification
      @verification = Verification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def verification_params
      params.require(:verification).permit(:first_name, :last_name, :email, :phone, :name, :statut, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rollee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/verifications/_form.html.erb
<%= simple_form_for(@verification) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :name %>
    <%= f.input :statut %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/verifications/edit.html.erb
<h1>Editing Verification</h1>

<%= render 'form', verification: @verification %>

<%= link_to 'Show', @verification %> |
<%= link_to 'Back', verifications_path %>

app/views/verifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Verifications</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Name</th>
      <th>Statut</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @verifications.each do |verification| %>
      <tr>
        <td><%= verification.first_name %></td>
        <td><%= verification.last_name %></td>
        <td><%= verification.email %></td>
        <td><%= verification.phone %></td>
        <td><%= verification.name %></td>
        <td><%= verification.statut %></td>
        <td><%= verification.user_id %></td>
        <td><%= link_to 'Show', verification %></td>
        <td><%= link_to 'Edit', edit_verification_path(verification) %></td>
        <td><%= link_to 'Destroy', verification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Verification', new_verification_path %>

app/views/verifications/new.html.erb
<h1>New Verification</h1>

<%= render 'form', verification: @verification %>

<%= link_to 'Back', verifications_path %>

app/views/verifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @verification.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @verification.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @verification.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @verification.phone %>
</p>

<p>
  <strong>Name:</strong>
  <%= @verification.name %>
</p>

<p>
  <strong>Statut:</strong>
  <%= @verification.statut %>
</p>

<p>
  <strong>User:</strong>
  <%= @verification.user_id %>
</p>

<%= link_to 'Edit', edit_verification_path(@verification) %> |
<%= link_to 'Back', verifications_path %>